name: dbt_test_intraday
run-name: dbt_test_intraday

on:
  workflow_dispatch:
    branches:
      - "main"
    
concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template.yml@pre-release/v4-beta
    with:
      target: test
      command_name: Run Observability & Recent Tests
      command: |
        dbt run -m "fsc_evm,tag:observability"
        dbt test -m "fsc_evm,tag:recent_test" --exclude "fsc_evm,tag:confirm_blocks" "fsc_evm.main_package.core.nft.tests.dbt_expectations_expect_row_values_to_have_recent_data_test_nft__ez_nft_transfers_recent_BLOCK_TIMESTAMP__hour__3 fsc_evm.main_package.core.nft.tests.dbt_expectations_expect_row_values_to_have_recent_data_test_nft__ez_nft_transfers_recent_INSERTED_TIMESTAMP__hour__3 fsc_evm.main_package.core.bronze.token_reads.dbt_expectations_expect_row_values_to_have_recent_data_bronze_api__token_reads__INSERTED_TIMESTAMP__day__1"
    secrets: inherit